### ISSUE TITLE
More improvements for stack traces with try...with

### ISSUE THREAD

**Issue by abbradar** [crowded/ply#12]
First of all - great job with https://github.com/dotnet/fsharp/issues/2741#issuecomment-668836655! It massively improves debugging experience. However, there's still at least one case when stack trace is lost: `try...with`. To reuse your example:

```
module PlyProgram

open System.Threading.Tasks
open FSharp.Control.Tasks
open System

let findDingbobbleById(x: int) = vtask {
    let! x = Task.Yield() // Force the Task to unwind the native stack
    return invalidOp "Oh no"
}

let dingbobbleFeature() = vtask {
    return! findDingbobbleById 1
}

let dingbobbleRoute() = vtask {
    try
        return! dingbobbleFeature()
    with
    | :? StackOverflowException as e -> return ()
}

[<EntryPoint>]
let main argv =
    try dingbobbleRoute().GetAwaiter().GetResult() |> ignore
    with ex -> Console.WriteLine(ex)
    0
```

With stack trace:

```
System.InvalidOperationException: Oh no
   at PlyProgram.dingbobbleRoute@18-6.Invoke(Exception _arg2) in /home/abbradar/projects/somefun/src/Program.fs:line 21
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at PlyProgram.main(String[] argv) in /home/abbradar/projects/somefun/src/Program.fs:line 26
```

Maybe we can improve this too?

EDIT: cleaned up the example

**Comment by NinoFloris** [comment]
Thank you, and yes you're completely right. I used to have a workaround in Ply for it, which I removed only recently as my fix for it got merged into the compiler https://github.com/dotnet/fsharp/pull/8882

All recent dotnet sdks/VS versions should ship this compiler fix as far as I know.

I will take a look in a bit which versions those may be and if the matrix is still too small I might just reintroduce the workaround :)

**Comment by abbradar** [comment]
Ahaha, I just found a workaround and you simultaneously sent this reply :D Thanks!

**Comment by NinoFloris** [comment]
I just read it, this is the workaround I had in place previously https://github.com/crowded/ply/commit/3973484fb0deaf0a851e49691008c2ccb3a6ee8f

**Comment by abbradar** [comment]
Yeah. I also see now I misunderstood how EDIs work; `Capture` actually captures stack trace of current exception, not of the current point of code. This means we can just use `EDI.Capture |> Throw` as you do in your F# patch, without need to pass captured EDI to the continuation.

Any idea how F# releases work? I see the patch has tag `v11.0.0-beta.20417.1` but I have no idea how does that correspond to F#/.NET Core versions.

Also, should we close this issue then?

**Comment by abbradar** [comment]
I updated .NET Core from 3.1.1 to 3.1.7 and got this fix. Thanks!
