### ISSUE TITLE
Question: Does Ply have the same performance issue with tail recursion as TaskBuilder.fs

### ISSUE THREAD

**Issue by ssiltanen** [crowded/ply#14]
Does Ply have the same performance issue with recursion as TaskBuilder.fs?

From TaskBuilder.fs documentation:

> In F# it is idiomatic to use tail recursion to implement loops more complex than a simple for or while.  works with some computation expressions (like the built-in F# async builder), but not with TaskBuilder.fs. As far as I know it is not possible to make this work with TPL tasks. C# async/await function are not tail-call optimized either, so at least this is consistent.  implement a loop that may iterate many times (or indefinitely), use a while loop instead of tail recursion.

**Comment by NinoFloris** [comment]
Yes it does, this is intrinsic to the way Task<T> works, in normal sequential async code a preceding task only completes once all it's antecedents have completed. A task isn't only a wrapper for a function/continuation like F#'s Async but it's also responsible for shipping the result back to the caller. As a result all tasks stay alive until the initial function completes with the result :/
