### ISSUE TITLE
open FSharp.Control.Tasks vs open FSharp.Control.Tasks.Builders

### ISSUE THREAD

**Issue by ursenzler** [crowded/ply#15]
read.me tells me to use the namespace `FSharp.Control.Tasks.Builders` that is marked as obsolete in code and I'm told to use `FSharp.Control.Tasks`.
And in release notes of FsToolkit.ErrorHandling: `FSharp.Control.Tasks.NonAffine/Affine`
Which namespace should be used?

**Comment by NinoFloris** [comment]
Yep, sorry about that, I have to update the docs. 

So the idea here is, Ply didn't used to have NonAffine/Affine just Affine builders (under the `Builders` module).

Previously we had an `AutoOpen` on `Builders` and we moved that `AutoOpen` to `Affine`, meaning open `FSharp.Control.Tasks` still opens the same type of builders :)

You can read more on when to open `Affine` vs `NonAffine` in the module summaries here:
https://github.com/crowded/ply/blob/master/ComputationBuilders.fs#L119

Hopefully that clears some of that up!

**Comment by ursenzler** [comment]
Thanks for the clarification!
I switched from TaskBuilder to Ply without any problems, great work.

Cheers,
Urs
